"""Resolve a committee tier list into an overrides file.

    python3 tools/resolve_tierlist.py data/tierlist-events-3v3.txt overrides.txt

Confident matches are written to the overrides file. Anything ambiguous or not
found is printed for a human to resolve — never guessed.
"""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from gibhub.api import Client  # noqa: E402
from gibhub.model import TIERS  # noqa: E402
from gibhub.render import strip_colors  # noqa: E402


def parse(path):
    tier, entries = None, []
    for line in open(path, encoding="utf-8"):
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        heading = re.match(r"^\[([A-Z])\]$", line)
        if heading:
            tier = heading.group(1)
            continue
        entries.append((line, tier))
    return entries


def candidates(name):
    """Progressively simpler forms of a Discord display name to search for."""
    forms = [name]
    # "h2o - awards missing" -> "h2o";  "CUPWINNER (vs mental)" -> "CUPWINNER"
    forms.append(re.split(r"\s+[-(–]", name)[0].strip())
    # "Gilbey / Mani" -> both halves
    if "/" in name:
        forms.extend(part.strip() for part in name.split("/"))
    # strip trailing punctuation/emoji noise
    forms.append(re.sub(r"[^\w\s.\[\]<>:*!-]", "", name).strip())
    forms.append(re.sub(r"[*]+$", "", forms[0]).strip())
    seen, out = set(), []
    for f in forms:
        if f and f.lower() not in seen:
            seen.add(f.lower())
            out.append(f)
    return out


def related(term, player):
    """Is this search hit plausibly the same person as the term?

    Fuzzy search happily returns 'Gilbey' for 'maNic' and 'juissi' for 'poshtat'.
    Requiring a shared substring kills those without rejecting 'teza' -> 'tezaXo'
    or 'lemr' -> 'eV!L*lemr'.
    """
    term = term.lower().strip()
    for candidate in (player.get("discord_nick") or "", strip_colors(player.get("nick"))):
        candidate = candidate.lower().strip()
        if candidate and (term in candidate or candidate in term):
            return True
    return False


def main(list_path, out_path):
    client = Client()
    resolved, unresolved = [], []

    for name, tier in parse(list_path):
        if tier not in TIERS:
            unresolved.append((name, tier, "bad tier heading", []))
            continue

        hit = None
        for form in candidates(name):
            data = (client.get("/players/search", {"q": form, "limit": 10}) or {}).get("data") or []
            if not data:
                continue
            lowered = form.lower()
            exact = [d for d in data
                     if (d.get("discord_nick") or "").lower() == lowered
                     or strip_colors(d.get("nick")).lower() == lowered]
            if len(exact) == 1:
                hit = (exact[0], form, "exact")
                break
            if len(exact) > 1:
                unresolved.append((name, tier, "%d exact matches" % len(exact), exact))
                hit = "ambiguous"
                break
            if len(data) == 1 and related(form, data[0]):
                hit = (data[0], form, "fuzzy")
                break
            if len(data) == 1:
                unresolved.append((name, tier, "only match looks unrelated", data))
                hit = "ambiguous"
                break
            unresolved.append((name, tier, "%d fuzzy matches, none exact" % len(data), data[:5]))
            hit = "ambiguous"
            break

        if hit is None:
            unresolved.append((name, tier, "no match", []))
        elif hit != "ambiguous":
            player, form, how = hit
            resolved.append((name, tier, player, form, how))

    # One player must not end up with two tiers: fuzzy matching can collapse two
    # distinct list entries onto the same account.
    by_id = {}
    for entry in resolved:
        by_id.setdefault(entry[2]["player_id"], []).append(entry)
    clashes = {pid: v for pid, v in by_id.items() if len(v) > 1}
    for pid, entries in clashes.items():
        for name, tier, player, form, how in entries:
            unresolved.append((
                name, tier,
                "collides with %s on the same account (%s)" % (
                    ", ".join(repr(e[0]) for e in entries if e[0] != name), pid),
                []))
    resolved = [e for e in resolved if e[2]["player_id"] not in clashes]

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("# Generated by tools/resolve_tierlist.py from %s\n" % list_path)
        f.write("# %d of %d names resolved. Review before trusting fuzzy matches.\n\n"
                % (len(resolved), len(resolved) + len(unresolved)))
        for name, tier, player, form, how in resolved:
            f.write("%s = %s  # %s%s\n" % (
                player["player_id"], tier,
                player.get("discord_nick") or strip_colors(player.get("nick")),
                "" if how == "exact" else "  <- FUZZY, listed as %r" % name))

    print("resolved %d of %d names -> %s" % (
        len(resolved), len(resolved) + len(unresolved), out_path))

    fuzzy = [r for r in resolved if r[4] != "exact"]
    if fuzzy:
        print("\n%d fuzzy match(es) to eyeball:" % len(fuzzy))
        for name, tier, player, form, _ in fuzzy:
            print("  [%s] %-24s -> %-18s (searched %r)" % (
                tier, name, player.get("discord_nick") or strip_colors(player.get("nick")), form))

    if unresolved:
        print("\n%d NOT resolved - add these by UUID yourself:" % len(unresolved))
        for name, tier, why, opts in unresolved:
            print("  [%s] %-24s %s" % (tier, name, why))
            for o in opts:
                print("        %s  %s (%s)" % (
                    o["player_id"], o.get("discord_nick") or "?", strip_colors(o.get("nick"))))


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2] if len(sys.argv) > 2 else "overrides.txt")
